// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_V_fev6TkcrIBInf9BUTLWK-XJQKCtNc',
    appId: '1:333597660008:web:0c7458084270324c1cfcdd',
    messagingSenderId: '333597660008',
    projectId: 'mylabgo-9dcb4',
    authDomain: 'mylabgo-9dcb4.firebaseapp.com',
    storageBucket: 'mylabgo-9dcb4.firebasestorage.app',
    measurementId: 'G-DWFLG2LPR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SIXjXwuUazNvTcTX2EwNTTKIQVQYcnE',
    appId: '1:333597660008:android:0baff4b315975a201cfcdd',
    messagingSenderId: '333597660008',
    projectId: 'mylabgo-9dcb4',
    storageBucket: 'mylabgo-9dcb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQGoyfe_gqEmRXLdxAODKfnc-NJsZH80',
    appId: '1:333597660008:ios:cf7a4bd2a3d2ee4c1cfcdd',
    messagingSenderId: '333597660008',
    projectId: 'mylabgo-9dcb4',
    storageBucket: 'mylabgo-9dcb4.firebasestorage.app',
    iosClientId: '333597660008-vfjgluvpc5qoqkejrobbfv3v9c95eado.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylabGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQGoyfe_gqEmRXLdxAODKfnc-NJsZH80',
    appId: '1:333597660008:ios:cf7a4bd2a3d2ee4c1cfcdd',
    messagingSenderId: '333597660008',
    projectId: 'mylabgo-9dcb4',
    storageBucket: 'mylabgo-9dcb4.firebasestorage.app',
    iosClientId: '333597660008-vfjgluvpc5qoqkejrobbfv3v9c95eado.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylabGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_V_fev6TkcrIBInf9BUTLWK-XJQKCtNc',
    appId: '1:333597660008:web:2edfb6f22f636f071cfcdd',
    messagingSenderId: '333597660008',
    projectId: 'mylabgo-9dcb4',
    authDomain: 'mylabgo-9dcb4.firebaseapp.com',
    storageBucket: 'mylabgo-9dcb4.firebasestorage.app',
    measurementId: 'G-J96B2JS4CN',
  );
}
